import { MetaFitColors } from "@/constants/theme";
import { StyleSheet } from "react-native";

export const estilos = StyleSheet.create({
  vistaScroll: {
    flex: 1,
  },
  contenidoScroll: {
    padding: 20,
    paddingBottom: 100,
  },
  contenedorInput: {
    marginBottom: 20,
    flexDirection: "row",
    alignItems: "center",
  },
  contenedorInputWrapper: {
    flex: 1,
  },
  input: {
    flex: 1,
    height: 50,
    borderWidth: 1,
    borderColor: MetaFitColors.border.light,
    borderRadius: 12,
    paddingHorizontal: 16,
    fontSize: 16,
    backgroundColor: MetaFitColors.background.card,
    color: MetaFitColors.text.primary,
  },
  inputReadOnly: {
    backgroundColor: MetaFitColors.background.beige,
    color: MetaFitColors.text.secondary,
  },
  contenedorInputReadOnly: {
    opacity: 0.7,
  },
  textoError: {
    fontSize: 12,
    marginTop: 4,
    marginLeft: 4,
    color: MetaFitColors.error,
  },
  contenedorInputConChevron: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    position: "relative",
  },
  contenedorChevron: {
    position: "absolute",
    right: 16,
    height: 50,
    justifyContent: "center",
    alignItems: "center",
  },
  contenedorInputConUnidad: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    height: 50,
    borderWidth: 1,
    borderColor: MetaFitColors.border.light,
    borderRadius: 12,
    backgroundColor: MetaFitColors.background.card,
    paddingRight: 8,
  },
  contenedorInputConUnidadReadOnly: {
    backgroundColor: MetaFitColors.background.beige,
  },
  inputConUnidad: {
    flex: 1,
    height: 50,
    paddingHorizontal: 16,
    fontSize: 16,
    color: MetaFitColors.text.primary,
  },
  inputConUnidadReadOnly: {
    backgroundColor: MetaFitColors.background.beige,
    color: MetaFitColors.text.secondary,
  },
  contenedorUnidad: {
    width: 50,
    height: 36,
    borderWidth: 1,
    borderColor: MetaFitColors.border.light,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: MetaFitColors.background.elevated,
    marginRight: 8,
  },
  contenedorUnidadReadOnly: {
    backgroundColor: MetaFitColors.background.beige,
  },
  textoUnidad: {
    fontSize: 16,
    fontWeight: "500",
  },
  contenedorEjercicio: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 6,
    backgroundColor: MetaFitColors.background.transparent,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: MetaFitColors.border.light,
    marginBottom: 20,
  },
  etiquetaEjercicio: {
    fontSize: 16,
    marginLeft: 10,
    flex: 1,
    color: MetaFitColors.text.tertiary,
  },
  grupoBotones: {
    flexDirection: "row",
    gap: 12,
  },
  botonToggle: {
    minWidth: 90,
    height: 35,
    borderWidth: 1,
    borderColor: MetaFitColors.border.light,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: MetaFitColors.background.card,
  },
  botonToggleDisabled: {
    opacity: 0.5,
  },
  botonToggleActivo: {
    backgroundColor: MetaFitColors.background.elevated,
    borderColor: MetaFitColors.button.primary,
  },
  textoBotonToggle: {
    fontSize: 16,
    fontWeight: "500",
  },
  contenedorBoton: {
    padding: 20,
    paddingBottom: 40,
    backgroundColor: MetaFitColors.background.white,
    borderTopWidth: 1,
    borderTopColor: MetaFitColors.border.light,
  },
  botonGuardar: {
    backgroundColor: MetaFitColors.button.primary,
    height: 52,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#2C3E50",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  botonGuardarDisabled: {
    opacity: 0.5,
  },
  textoBotonGuardar: {
    fontSize: 17,
    fontWeight: "700",
    color: MetaFitColors.text.white,
    letterSpacing: 0.2,
  },
  overlayModal: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    justifyContent: "center",
    alignItems: "center",
  },
  contenidoModal: {
    backgroundColor: MetaFitColors.background.card,
    borderRadius: 20,
    padding: 20,
    width: "85%",
    maxWidth: 400,
    borderWidth: 1,
    borderColor: MetaFitColors.border.light,
  },
  tituloModal: {
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 20,
    textAlign: "center",
  },
  opcionModal: {
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: MetaFitColors.border.light,
    backgroundColor: MetaFitColors.background.elevated,
  },
  opcionModalSeleccionada: {
    backgroundColor: MetaFitColors.background.elevated,
    borderColor: MetaFitColors.button.primary,
  },
  textoOpcionModal: {
    fontSize: 16,
    fontWeight: "500",
    textAlign: "center",
  },
  textoOpcionModalSeleccionada: {
    fontWeight: "600",
  },
  botonCancelarModal: {
    paddingVertical: 12,
    marginTop: 8,
    alignItems: "center",
  },
  textoCancelarModal: {
    fontSize: 16,
    fontWeight: "500",
  },
});

