import { MetaFitColors } from "@/constants/theme";
import { StyleSheet } from "react-native";

export const estilos = StyleSheet.create({
  vistaScroll: {
    flex: 1,
  },
  contenidoScroll: {
    padding: 20,
    paddingBottom: 100,
  },
  contenedorInput: {
    marginBottom: 20,
    flexDirection: "row",
    alignItems: "center",
  },
  contenedorInputWrapper: {
    flex: 1,
  },
  input: {
    flex: 1,
    height: 50,
    borderWidth: 1,
    borderColor: MetaFitColors.border.light,
    borderRadius: 12,
    paddingHorizontal: 16,
    fontSize: 16,
    backgroundColor: MetaFitColors.background.white,
    color: MetaFitColors.text.primary,
  },
  textoError: {
    fontSize: 12,
    marginTop: 4,
    marginLeft: 4,
    color: MetaFitColors.error,
  },
  contenedorInputConChevron: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    position: "relative",
  },
  contenedorChevron: {
    position: "absolute",
    right: 16,
    height: 50,
    justifyContent: "center",
    alignItems: "center",
  },
  contenedorInputConUnidad: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    height: 50,
    borderWidth: 1,
    borderColor: MetaFitColors.border.light,
    borderRadius: 12,
    backgroundColor: MetaFitColors.background.white,
    paddingRight: 8,
  },
  inputConUnidad: {
    flex: 1,
    height: 50,
    paddingHorizontal: 16,
    fontSize: 16,
    color: MetaFitColors.text.primary,
  },
  contenedorUnidad: {
    width: 50,
    height: 36,
    borderWidth: 1,
    borderColor: MetaFitColors.border.light,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: MetaFitColors.background.white,
    marginRight: 8,
  },
  textoUnidad: {
    fontSize: 16,
    fontWeight: "500",
  },
  contenedorEjercicio: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 6,
    backgroundColor: MetaFitColors.background.transparent,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: MetaFitColors.border.light,
    marginBottom: 20,
  },
  etiquetaEjercicio: {
    fontSize: 16,
    marginLeft: 10,
    flex: 1,
    color: MetaFitColors.text.tertiary,
  },
  grupoBotones: {
    flexDirection: "row",
    gap: 12,
  },
  botonToggle: {
    minWidth: 90,
    height: 35,
    borderWidth: 1,
    borderColor: MetaFitColors.border.light,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: MetaFitColors.background.white,
  },
  botonToggleActivo: {
    backgroundColor: MetaFitColors.button.active,
    borderColor: MetaFitColors.background.transparent,
  },
  textoBotonToggle: {
    fontSize: 16,
    fontWeight: "500",
  },
  contenedorBoton: {
    padding: 20,
    paddingBottom: 40,
    backgroundColor: MetaFitColors.background.white,
    borderTopWidth: 1,
    borderTopColor: MetaFitColors.border.divider,
  },
  botonGuardar: {
    backgroundColor: MetaFitColors.button.primary,
    height: 50,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  textoBotonGuardar: {
    fontSize: 18,
    fontWeight: "bold",
    color: MetaFitColors.text.white,
  },
  overlayModal: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  contenidoModal: {
    backgroundColor: MetaFitColors.background.white,
    borderRadius: 16,
    padding: 20,
    width: "80%",
    maxWidth: 400,
  },
  tituloModal: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 20,
    textAlign: "center",
  },
  opcionModal: {
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: MetaFitColors.border.light,
    backgroundColor: MetaFitColors.background.white,
  },
  opcionModalSeleccionada: {
    backgroundColor: MetaFitColors.button.active,
    borderColor: MetaFitColors.button.active,
  },
  textoOpcionModal: {
    fontSize: 16,
    fontWeight: "500",
    textAlign: "center",
  },
  textoOpcionModalSeleccionada: {
    fontWeight: "600",
  },
  botonCancelarModal: {
    paddingVertical: 12,
    marginTop: 8,
    alignItems: "center",
  },
  textoCancelarModal: {
    fontSize: 16,
    fontWeight: "500",
  },
});

